config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  resources :clients do
    resources :documents
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :documents
  validates :prenom, presence: true
  validates :nom, presence: true
  validates :adresse, presence: true
  validates :cp, presence: true
  validates :ville, presence: true
  validates :pays, presence: true
  validates :telephone_portable, presence: true
  validates :email, presence: true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :client
  enum types: %i[Devis Facture]
  enum statut: %i[Creation Attente Accepté Refusé Terminé]
  validates :designation, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :rememberable
  devise :database_authenticatable, :validatable
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[prenom nom adresse cp ville pays telephone_fixe telephone_portable admin reponsable])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[prenom nom adresse cp ville pays telephone_fixe telephone_portable admin reponsable])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = policy_scope(Client.all)
    # authorize @clients
    @clients = @clients.where("#{params[:search]} ILIKE ?", "#{params[:query]}%") if params[:query].present?
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "clients/list", locals: { clients: @client }, formats: [:html] }
    end
  end

  def new
    @client = Client.new
    authorize @client
  end

  def create
    @client = Client.new(client_params)
    authorize @client
    if @client.save
      redirect_to clients_path
    else
      puts @client.errors.messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @client = Client.find(params[:id])
    authorize @client
  end

  def update
    @client = Client.find(params[:id])
    authorize @client
    if @client.update(client_params)
      redirect_to client_path
    else
      render :new, status: { clients: client }
    end
  end

  def show
    @client = Client.find(params[:id])
    authorize @client
  end

  def destroy
    @client = Client.find(params[:id])
    authorize @client
    if @client.destroy
      redirect_to clients_path
    else
      render :new, status: { clients: client }
    end
  end

  private

  def client_params
    params.require(:client).permit(:prenom, :nom, :adresse, :cp, :ville, :pays, :telephone_fixe, :telephone_portable,
                                    :email)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def show
    @document = Document.find(params[:id])
    authorize @document
  end

  def new
    @document = Document.new
    authorize @document
  end

  def create
    puts(params)
    @document = Document.new(document_params)
    @document.user_id = current_user.id
    @document.client_id = params[:client_id]
    @document.montant = 0.0
    # @document.types = 0
    @document.statut = 0
    authorize @document
    if @document.save
      redirect_to client_document_path(params[:client_id], @document)
      # redirect_to client_path(params[:client_id])
    else
      puts @document.errors.messages
      # render :new, status: :unprocessable_entity
    end
  end

  def index
    @documents = policy_scope(Document.all)
    # @documents = @documents.where("#{params[:search]} ILIKE ?", "#{params[:query]}%") if params[:query].present?
    # respond_to do |format|
    #   format.html # Follow regular flow of Rails
    #   format.text { render partial: "clients/list", locals: { clients: @client }, formats: [:html] }
    # end
  end

  def destroy
    puts(params)
    @document = Document.find(params[:id])
    authorize @document
    if @document.destroy
      flash.alert = "Devis supprimé"
      redirect_to controller: "clients", action: "show"
    else
      flash.alert = "impossible de suprimer le devis"
    end
  end

  private

  def document_params
    params.require(:document).permit(:types, :statut, :commentaire, :user_id, :client_id, :montant, :designation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_edit.html.erb
<!-- Button trigger modal -->
<button type="button" class="fa-solid fa-pen-to-square" data-bs-toggle="modal" data-bs-target="#editModal">
</button>
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-style-header">
        <h5 class="modal-title" id="editModalLabel">Modifier client</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-style-body">
          <%= simple_form_for (client) do |f|%>
            <%= f.input :prenom%>
            <%= f.input :nom%>
            <%= f.input :adresse%>
            <%= f.input :cp%>
            <%= f.input :ville%>
            <%= f.input :pays%>
            <%= f.input :telephone_fixe%>
            <%= f.input :telephone_portable%>
            <%= f.input :email%>
      </div>
      <div class="modal-footer modal-style-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary',method: :patch%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/_list.html.erb
<div class= "container-clients" data-search-clients-target = "list">
  <%= render "clients/new"%>
  <table class="table table-hover list-clients">
    <thead>
      <tr class= "titre">
        <th scope="col">Détails</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Adresse</th>
        <th scope="col">Code postal</th>
        <th scope="col">Ville</th>
        <th scope="col">pays</th>
        <th scope="col">Téléphone</th>
        <th scope="col">Téléphone portable</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client|%>
        <tr>
          <td><%= link_to client_path(client) do%>
            <i class="fa-solid fa-pen-to-square"></i>
          <%end%></td>
          <td><%= client.prenom%></td>
          <td><%= client.nom%></td>
          <td><%= client.adresse%></td>
          <td><%= client.cp%></td>
          <td><%= client.ville%></td>
          <td><%= client.pays%></td>
          <td><%= client.telephone_fixe%></td>
          <td><%= client.telephone_portable%></td>
          <td><%= client.email%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/clients/_listDevis.html.erb
<div class= "container-clients m-4">
  <table class="table table-hover list-clients">
    <thead>
      <tr class= "titre">
        <th scope="col">Editer</th>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Statut</th>
        <th scope="col">Création</th>
        <th scope="col">Modification</th>
        <th scope="col">Désignation</th>
        <th scope="col">Montant</th>
      </tr>
    </thead>
    <tbody>
      <% documents = policy_scope(Document.all)%>
      <% documents.each do |document|%>
        <% if document.client.id == @client.id%>
          <tr>
            <td><%= link_to client_document_path(@client,document) do%>
              <i class="fa-solid fa-pen-to-square"></i>
            <%end%></td>
            <td><%= document.id%></td>
            <td><%= document.types%></td>
            <td><%= document.statut%></td>
            <td><%= document.created_at.strftime('%d-%b-%Y %H:%M')%></td>
            <td><%= document.updated_at.strftime('%d-%b-%Y %H:%M')%></td>
            <td><%= document.designation%></td>
            <td><%= document.montant%></td>
          </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/clients/_listFacture.html.erb
<div class= "container-clients-devis mx-4">
  <%= render "clients/newFacture"%>
  <table class="table table-hover list-clients">
    <thead>
      <tr class= "titre">
        <th scope="col">Editer</th>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Statut</th>
        <th scope="col">Création</th>
        <th scope="col">Modification</th>
        <th scope="col">Désignation</th>
        <th scope="col">Montant</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% documents = policy_scope(Document.all)%>
      <% documents.each do |document|%>
        <% if document.client.id == @client.id && document.types == "Facture"%>
          <tr>
            <td><%= link_to client_document_path(@client,document) do%>
              <i class="fa-solid fa-pen-to-square"></i>
            <%end%></td>
            <td><%= document.id%></td>
            <td><%= document.types%></td>
            <td><%= document.statut%></td>
            <td><%= document.created_at.strftime('%d-%b-%Y %H:%M')%></td>
            <td><%= document.updated_at.strftime('%d-%b-%Y %H:%M')%></td>
            <td><%= document.designation%></td>
            <td><%= document.montant%></td>
            <% if document.montant == 0 || policy(@document).destroy? %>
              <td><%= link_to client_document_path(@client,document), data: {turbo: true, turbo_method: :delete }  do %>
                <i class="fa-solid fa-trash"></i>
              <% end %></td>
            <% end %>
          </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

app/views/clients/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border border-secondary rounded navbar-search">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarListClients" aria-controls="navbarListClients" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarListClients">
          <%= form_with url: clients_path, method: :get, html: { data: {search_clients_target: "form"} } do |f|%>
            <%= f.text_field :query, class: "form-control",
                              placeholder: "Rechercher",
                              value: params[:query],
                              data: {search_clients_target: "input",
                              action:"keyup->search-clients#update"}%>
          <% end%>
          <select class="form-select" aria-label="Default select example" data-search-clients-target= "searchParam">
            <option value="nom">Nom</option>
            <option value="cp">Code postal</option>
            <option value="telephone_portable">Téléphone portable</option>
            <option value="email">Email</option>
          </select>
    </div>
  </div>
</div>

app/views/clients/_new.html.erb
<!-- Button trigger modal -->
  <i type="button" class="fa-solid fa-square-plus fa-xl modal-btn" data-bs-toggle="modal" data-bs-target="#newModal"></i> Nouveau
<!-- Modal -->
<div class="modal fade" id="newModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="newModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-style-header">
        <h5 class="modal-title" id="newModalLabel">Nouveau client</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%client = Client.new%>
          <%= simple_form_for client do |f|%>
      <div class="modal-body modal-style-body">
        <%= f.input :prenom%>
        <%= f.input :nom%>
        <%= f.input :adresse%>
        <%= f.input :cp%>
        <%= f.input :ville%>
        <%= f.input :pays%>
        <%= f.input :telephone_fixe%>
        <%= f.input :telephone_portable%>
        <%= f.input :email%>
      </div>
      <div class="modal-footer modal-style-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' if policy(Client).new?%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/_newDevis.html.erb
<!-- Button trigger modal -->
  <i type="button" class="fa-solid fa-square-plus fa-xl modal-btn" data-bs-toggle="modal" data-bs-target="#newDevisModal"></i> Nouveau
<!-- Modal -->
<div class="modal fade" id="newDevisModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="newDevisModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-style-header">
        <h5 class="modal-title" id="newDevisModalLabel">Nouveau Devis</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% document = Document.new%>
      <%= simple_form_for [@client,document] do |f|%>
      <div class="modal-body modal-style-body">
        <%= f.input :types, collection: Document.types.keys, selected: ["Devis"]%>
        <%= f.input :client_id, as: :hidden, input_html: {value: @client.id},disabled: true%>
        <%= f.input :designation%>
        <%= f.input :commentaire, as: :text%>
      </div>
      <div class="modal-footer modal-style-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' if policy(Document).new?%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/_newFacture.html.erb
<!-- Button trigger modal -->
  <i type="button" class="fa-solid fa-square-plus fa-xl modal-btn" data-bs-toggle="modal" data-bs-target="#newFactureModal"></i> Nouvelle
<!-- Modal -->
<div class="modal fade" id="newFactureModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="newFactureModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-style-header">
        <h5 class="modal-title" id="newFactureModalLabel">Nouvelle Facture</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% document = Document.new%>
      <%= simple_form_for [@client,document] do |f|%>
      <div class="modal-body modal-style-body">
        <%= f.input :types, collection: Document.types.keys, selected: ["Facture"]%>
        <%= f.input :client_id, as: :hidden, input_html: {value: @client.id},disabled: true%>
        <%= f.input :designation%>
        <%= f.input :commentaire, as: :text%>
      </div>
      <div class="modal-footer modal-style-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' if policy(Document).new?%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/_update.html.erb
<i type="button" class="fa-solid fa-pen-to-square modifier" data-bs-toggle="modal" data-bs-target="#updateClientModal"></i> Modifier les informations
<div class="modal fade" id="updateClientModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="updateClientModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-style-header">
        <h5 class="modal-title" id="updateClientModalLabel">Modifier les informations client</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @client do |f|%>
      <div class="modal-body modal-style-body">
        <%= f.input :prenom%>
        <%= f.input :nom%>
        <%= f.input :adresse%>
        <%= f.input :cp%>
        <%= f.input :ville%>
        <%= f.input :pays%>
        <%= f.input :telephone_fixe%>
        <%= f.input :telephone_portable%>
        <%= f.input :email%>
      </div>
      <div class="modal-footer modal-style-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%puts(policy(Client).update?)%>
        <%= f.button :submit, class: 'btn btn-primary' if policy(Client).update?%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class= "clients-background  border border-secondary rounded">
  <div class="text-center">
    <h1>CLIENTS</h1>
  </div>
  <div data-controller="search-clients">
    <%= render "clients/navbar"%>
    <%= render "clients/list"%>
  </div>
</div>

app/views/clients/show.html.erb
<div class="container clients-background">
  <h2 class="text-center">INFORMATIONS CLIENT</h2>
  <div class="row mx-4">
    <div class="col-12 col-lg-8 show-client">
      <ul>
        <li><strong><%= @client.prenom%></strong> <strong><%= @client.nom%></strong></li>
        <li><strong><%= @client.adresse%></strong></li>
        <li><strong><%= @client.cp%> <strong><%= @client.ville%></strong></strong> <strong><%= @client.pays%></strong></li>
        <li><strong><%= @client.telephone_fixe%></strong></li>
        <li><strong><%= @client.telephone_portable%></strong></li>
        <li><strong><%= @client.email%></strong></li>
      </ul>
      <%= render "clients/update"%>
    </div>
  </div>
  <h2 class="text-center">DEVIS</h2>
  <%= render "clients/listDevis"%>
  <h2 class="text-center">FACTURE</h2>
  <%= render "clients/listFacture"%>
</div>

app/views/documents/show.html.erb
<div class= "clients-background  border border-secondary rounded">
  <h1 class="text-center"><%= @document.types%> N°: <%= @document.id%> </h1>
  <h2>Client :</h2>
  <ul>
    <li><%= @document.client.prenom%> <%= @document.client.nom%></li>
    <li><%= @document.client.adresse%></li>
    <li><%= @document.client.cp%> <%= @document.client.ville%>, <%= @document.client.pays%></li>
    <li><%= @document.client.telephone_fixe%></li>
    <li><%= @document.client.telephone_portable%></li>
    <li><%= @document.client.email%></li>
  </ul>
 <%= link_to "Retour", client_path(@document.client)%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>RailsGestionEntrepreneur</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= render "shared/flashes" %>
    <div class = "container-fluid d-flex p-0" style= "height: calc(100vh - 74px);">
      <%= render "shared/menu" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class= "home-background text-center border border-secondary rounded">
  <h1>Gestionnaire d'entreprise</h1>
  <p>Pilotez toute votre entreprise</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon menu border border-secondary rounded">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav me-auto flex-column">
        <% if user_signed_in? %>
          <li class = "list-menu pt-4 border-bottom border-dark"><%= link_to "Clients", clients_path %></li>
          <li class = "list-menu border-bottom border-dark" ><%= link_to "Fournisseurs", "#"%></li>
          <li class = "list-menu border-bottom border-dark"><%= link_to "Articles", "#" %></li>
          <% if current_user.admin? %>
            <li class = "list-menu border-bottom border-dark"><%= link_to "admin", rails_admin_path %></li>
          <% end %>
        <% else %>
            <li class = "list-menu pt-4 border-bottom border-dark"><%= "Clients"%></li>
            <li class = "list-menu border-bottom border-dark" ><%= "Fournisseurs"%></li>
            <li class = "list-menu border-bottom border-dark"><%= "Articles"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border border-secondary rounded">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "home_house_couleur.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <p class= "nav-link"><%= "Bienvenue #{current_user.prenom} #{current_user.nom}"%></p>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "login_couleur.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>